export const ADD_NEW_TASK_START = "ADD_NEW_TASK_START";
export const ADD_NEW_TASK_SUCCESS = "ADD_NEW_TASK_SUCCESS";
export const ADD_NEW_TASK_FAILED = "ADD_NEW_TASK_FAILED";

export const GET_LABELS_START = "GET_LABELS_START";
export const GET_LABELS_SUCCESS = "GET_LABELS_SUCCESS";
export const GET_LABELS_FAILED = "GET_LABELS_FAILED";

export const ADD_NEW_LABEL = "ADD_NEW_LABEL";
export const ADD_NEW_LABEL_SUCCESS = "ADD_NEW_LABEL_SUCCESS";
export const ADD_NEW_LABEL_FAILED = "ADD_NEW_LABEL_FAILED";

export const GET_ALL_TASKS = "GET_ALL_TASKS";
export const GET_ALL_TASKS_SUCCESS = "GET_ALL_TASKS_SUCCESS";
export const GET_ALL_TASKS_FAILED = "GET_ALL_TASKS_FAILED";

export const USER_LOGIN = "USER_LOGIN";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAILED = "USER_LOGIN_FAILED";

export const USER_SIGNUP = "USER_SIGNUP";
export const USER_SIGNUP_SUCCESS = "USER_SIGNUP_SUCCESS";
export const USER_SIGNUP_FAILED = "USER_SIGNUP_FAILED";

export const DELETE_TASK = "DELETE_TASK";
export const DELETE_TASK_FAILED = "DELETE_TASK_FAILED";
export const DELETE_TASK_SUCCESS = "DELETE_TASK_SUCCESS";

export const EDIT_TASK = "EDIT_TASK";
export const EDIT_TASK_FAILED = "EDIT_TASK_FAILED";
export const EDIT_TASK_SUCCESS = "EDIT_TASK_SUCCESS";

export const LOGOUT = "LOGOUT";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAILED = "LOGOUT_FAILED";
